export const AUTH = {
    LOGIN_REQUEST: 'LOGIN_REQUEST',
    LOGIN_SUCCESS: 'LOGIN_SUCCESS',
    LOGOUT_REQUEST: 'LOGOUT_REQUEST',
    LOGOUT_SUCCESS: 'LOGOUT_SUCCESS'
};

export const ERROR = {
    CREATE: 'CREATE_ERROR',
    DELETE: 'DELETE_ERROR'
};