export const AUTH = {
    LOGIN_WITH_GOOGLE: 'LOGIN_WITH_GOOGLE',
    LOGIN_WITH_EMAIL: 'LOGIN_WITH_EMAIL',
    LOGIN_SUCCESS: 'LOGIN_SUCCESS',
    LOGOUT_REQUEST: 'LOGOUT_REQUEST',
    LOGOUT_SUCCESS: 'LOGOUT_SUCCESS',
    REGISTER_REQUEST: 'REGISTER_REQUEST'
};

export const ERROR = {
    CREATE: 'CREATE_ERROR',
    DELETE: 'DELETE_ERROR'
};